# Generated by Django 4.0.3 on 2022-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='bmi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
